packages:
  - "."   
  - "src/agents"
  - "src/api"
  - "src/config"
  - "src/platforms"
  - "src/server"
  - "src/types"
  - "src/utils"
  - "src/core" 
  - "plugins/hello-world-plugin"
  - "shared-interfaces"
